In [1]:
import numpy as np

In [69]:
BOARD_SIZE=(6,6) # y,x

class Board():
    def __init__(self):
        self.state = np.zeros(BOARD_SIZE)

    def has_won(self):
        """
        Returns the player that won, or False otherwise
        """
        winner = False
        # Look for horizontal lines
        for y in range(BOARD_SIZE[0]):
            for x in range(BOARD_SIZE[1]-3):
                line = self.state[y, x:x+4]
                unique_players_in_line = np.unique(line)
                if unique_players_in_line.size == 1:
                    if unique_players_in_line[0] != 0:
                        return unique_players_in_line[0]

        # Look for vertical lines
        for x in range(BOARD_SIZE[1]):
            for y in range(BOARD_SIZE[0]-3):
                line = self.state[y:y+4, x]
                unique_players_in_line = np.unique(line)
                if unique_players_in_line.size == 1:
                    if unique_players_in_line[0] != 0:
                        return unique_players_in_line[0]

        # Look for diagonal lines (y=x+b)
        for x in range(BOARD_SIZE[1]-3):
            for y in range(BOARD_SIZE[0]-3):
                line = np.array([self.state[y+i, x+i] for i in range(4)])
                unique_players_in_line = np.unique(line)
                if unique_players_in_line.size == 1:
                    if unique_players_in_line[0] != 0:
                        return unique_players_in_line[0]

        # Look for diagonal lines (y=-x+b)
        for x in range(3,BOARD_SIZE[1],1):
            for y in range(BOARD_SIZE[0]-3):
                line = np.array([self.state[y+i, x-i] for i in range(4)])
                unique_players_in_line = np.unique(line)
                if unique_players_in_line.size == 1:
                    if unique_players_in_line[0] != 0:
                        return unique_players_in_line[0]

        return winner
    
    def can_play(self):
        """
        Returns True if there are moves available
        """
        top_row = self.state[0]
        return np.any(top_row == 0)

    def play(self, player, move):
        """
        Puts a piece in one of the columns
        """
        if not self._validate_move(move):
            print('Move {} not valid'.format(move))
            return False
        x = move
        y = BOARD_SIZE[0]-1
        while y >= 0 and self.state[y, x] != 0:
            y -= 1
        if y >= 0:
            self.state[y, x] = player
            return self.state
        else:
            print('Move {} is out of range (stack overflow)'.format(move))
            return False
    
    def print_board(self):
        print(self.state)

    def _validate_move(self, move):
        """
        Checks if the move is valid and returns True if it is
        """
        return self.state[0,move] == 0


In [86]:
board = Board()

In [96]:
state = board.play(1,1)
print(state)
winner = board.has_won()
print(winner)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 2. 0. 0.]
 [0. 1. 2. 2. 0. 0.]
 [1. 2. 2. 2. 0. 0.]]
1.0
